### ISSUE TITLE
How much space it used Instal+post instal model download

### ISSUE THREAD

**Issue by tukangcode** [rupeshs/instantidcpu#2]
Hi hello, i bit have storage crisis so i want know how much disk size cost for instal and model.
thanks.

**Comment by rupeshs** [comment]
30GB 
Models folder - 5 GB
HF Cache folder sdxl turbo - 25GB
If you already have sdxl turbo cached you only need 5GB

**Comment by tukangcode** [comment]
thanks for info, seem i really need upgrade my potato laptop now.
